#!/usr/bin/env python3
"""
Claude Code PR Review Agent
Bounty: $150
Issue: #4
Repository: claude-builders-bounty/claude-builders-bounty
"""

import os
import sys
import json
import argparse
import subprocess
from typing import Dict, List, Optional
from pathlib import Path

class PRReviewAgent:
    """Claude Code sub-agent for reviewing pull requests"""
    
    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.environ.get('ANTHROPIC_API_KEY')
        if not self.api_key:
            raise ValueError("ANTHROPIC_API_KEY not found in environment")
    
    def fetch_pr_diff(self, pr_url: str) -> str:
        """Fetch PR diff from GitHub"""
        # Parse PR URL
        # Format: https://github.com/owner/repo/pull/123
        parts = pr_url.split('/')
        if len(parts) < 7 or 'pull' not in parts:
            raise ValueError(f"Invalid PR URL format: {pr_url}")
        
        owner = parts[3]
        repo = parts[4]
        pr_number = parts[6]
        
        # Fetch diff using GitHub API
        api_url = f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}"
        
        # Use curl to fetch diff
        cmd = [
            'curl', '-s',
            '-H', 'Accept: application/vnd.github.v3.diff',
            api_url
        ]
        
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, check=True)
            return result.stdout
        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"Failed to fetch PR diff: {e}")
    
    def analyze_pr(self, diff: str) -> Dict:
        """Analyze PR diff and generate review"""
        
        # Prepare prompt for Claude
        prompt = f"""Review the following pull request diff and provide a structured code review in Markdown format.

Focus on:
1. Code quality and best practices
2. Potential bugs or errors
3. Performance concerns
4. Security issues
5. Documentation completeness
6. Test coverage suggestions

PR Diff:
```diff
{diff}
```

Provide your review in the following Markdown format:

## 📋 Pull Request Review

### Summary
[Brief summary of changes]

### 🎯 Code Quality
- [Issues/suggestions]

### 🐛 Potential Issues
- [Bugs or errors]

### ⚡ Performance
- [Performance concerns]

### 🔒 Security
- [Security issues]

### 📚 Documentation
- [Documentation feedback]

### ✅ Test Coverage
- [Test suggestions]

### 💡 Recommendations
1. [Top recommendation]
2. [Second recommendation]
3. [Third recommendation]

### Overall Assessment
[Approve/Request Changes/Comment] - [Brief rationale]
"""
        
        # Call Claude API
        review = self._call_claude_api(prompt)
        return review
    
    def _call_claude_api(self, prompt: str) -> Dict:
        """Call Claude API with prompt"""
        
        # Prepare API request
        api_data = {
            "model": "claude-sonnet-4-20250514",
            "max_tokens": 2048,
            "messages": [
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        }
        
        # Use curl to call Claude API
        cmd = [
            'curl', '-s', '-X', 'POST',
            'https://api.anthropic.com/v1/messages',
            '-H', f'x-api-key: {self.api_key}',
            '-H', 'Content-Type: application/json',
            '-H', 'anthropic-version: 2023-06-01',
            '-d', json.dumps(api_data)
        ]
        
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, check=True)
            response = json.loads(result.stdout)
            
            # Extract review text from response
            if 'content' in response and len(response['content']) > 0:
                return {
                    'review': response['content'][0].get('text', ''),
                    'usage': response.get('usage', {})
                }
            else:
                raise RuntimeError(f"Unexpected API response format: {response}")
                
        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"Failed to call Claude API: {e}")
        except json.JSONDecodeError as e:
            raise RuntimeError(f"Failed to parse API response: {e}")
    
    def format_review(self, review_data: Dict) -> str:
        """Format review as structured Markdown"""
        review = review_data.get('review', '')
        usage = review_data.get('usage', {})
        
        # Add metadata
        formatted = f"{review}\n\n---\n\n"
        formatted += f"**Generated by Claude Code PR Review Agent**\n"
        formatted += f"**Model**: claude-sonnet-4-20250514\n"
        formatted += f"**Tokens Used**: {usage.get('total_tokens', 'N/A')}\n"
        
        return formatted
    
    def review_pr(self, pr_url: str, output_file: Optional[str] = None) -> str:
        """Main method to review a PR"""
        
        print(f"🔍 Fetching PR diff from: {pr_url}")
        diff = self.fetch_pr_diff(pr_url)
        
        print(f"🤖 Analyzing PR with Claude...")
        review_data = self.analyze_pr(diff)
        
        formatted_review = self.format_review(review_data)
        
        if output_file:
            Path(output_file).write_text(formatted_review)
            print(f"✅ Review saved to: {output_file}")
        else:
            print("\n" + formatted_review)
        
        return formatted_review


def main():
    """CLI entry point"""
    parser = argparse.ArgumentParser(
        description='Claude Code PR Review Agent - Review pull requests using AI',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Review a PR and print to stdout
  claude-review --pr https://github.com/owner/repo/pull/123

  # Review a PR and save to file
  claude-review --pr https://github.com/owner/repo/pull/123 --output review.md

  # Use custom API key
  claude-review --pr https://github.com/owner/repo/pull/123 --api-key YOUR_KEY
"""
    )
    
    parser.add_argument(
        '--pr',
        required=True,
        help='GitHub PR URL (e.g., https://github.com/owner/repo/pull/123)'
    )
    
    parser.add_argument(
        '--output', '-o',
        help='Output file path for review (optional)'
    )
    
    parser.add_argument(
        '--api-key',
        help='Anthropic API key (optional, reads from ANTHROPIC_API_KEY env var)'
    )
    
    args = parser.parse_args()
    
    try:
        agent = PRReviewAgent(api_key=args.api_key)
        agent.review_pr(args.pr, args.output)
        sys.exit(0)
    except Exception as e:
        print(f"❌ Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
